/**
 * ╔══════════════════════════════════════════════════════════════════════════════╗
 * ║ AUTOGENERATED — do not edit by hand                                          ║
 * ║   pnpm sync-versions                                                         ║
 * ╚══════════════════════════════════════════════════════════════════════════════╝
 */

export function packageManagerSpecifier(pm: "bun" | "pnpm" | "npm"): string {
  switch (pm) {
    case "bun":
      return "bun@1.1.42";
    case "pnpm":
      return "pnpm@10.14.0";
    case "npm":
      return "npm@10.9.2";
  }
}
