// This file is auto-generated by the TanStack Router Vite plugin on dev/build.
// Scaffold stub: overrides the frontend default so `/login` is known before first `vite dev`
// when Better Auth mounts the TanStack login route.
import type { Route as RootRoute } from "./routes/__root";
import type { Route as IndexRoute } from "./routes/index";
import type { Route as LoginRoute } from "./routes/login";

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { parentRoute: typeof RootRoute; preLoaderRoute: typeof IndexRoute };
    "/login": { parentRoute: typeof RootRoute; preLoaderRoute: typeof LoginRoute };
  }
}

export const routeTree: any = undefined as any;
