// This file is auto-generated by the TanStack Router Vite plugin on dev/build.
// The stub below makes `tsc --noEmit` pass on a fresh install, before the
// first `vite dev`. The plugin overwrites it with real route types.
import type { Route as RootRoute } from "./routes/__root";
import type { Route as IndexRoute } from "./routes/index";

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { parentRoute: typeof RootRoute; preLoaderRoute: typeof IndexRoute };
  }
}

export const routeTree: any = undefined as any;
